### ISSUE TITLE
Label Display Only Showing Row Number 

### ISSUE THREAD

**Issue by abresler** [sinhrks/ggfortify#20] opened 2015-02-08 20:01 UTC
For some reason when I try to plot labels I can't ever  the actual labels even after renaming the rows

**Comment by sinhrks** [comment] 2015-02-09 11:42
Thanks for the report. The issue is depending on {dplyr} version, and expected to be fixed in #21. Colud you try confirm?

**Closed** 2015-02-09 11:41 UTC

**Comment by abresler** [comment] 2015-02-09 12:11
Will give it a try again in a little.

Wonderful package, thanks for all the work you put into it

-- 
Alex Bresler

ASBC LLLC
asbcllc.com
917-455-0239

abresler@asbcllc.com
@abresler
