### ISSUE TITLE
Error on loading ggfortify

### ISSUE THREAD

**Issue by richardtc** [sinhrks/ggfortify#45] opened 2015-06-18 17:22 UTC
Hi 
 
I'm trying to plot acf outputs with ggplot2, and trying to use ggfortify, but get the error below.

Best,
Richard

> library(ggplot2)
> library(ggfortify)
Loading required package: scales
Error in unloadNamespace(package) : 
  namespace ‘scales’ is imported by ‘ggplot2’ so cannot be unloaded
Error in library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc) : 
  Package ‘scales’ version 0.2.4 cannot be unloaded

Using R on Ubuntu Trusty: R:  3.2.0-4trusty0

**Comment by richardtc** [comment] 2015-06-18 17:39
Also now get error on loading ggplot2

> library(ggplot2)
Error in get(method, envir = home) : 
  lazy-load database '/home/rcooper/R/x86_64-pc-linux-gnu-library/3.2/scales/R/scales.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘ggplot2’
>

**Comment by richardtc** [comment] 2015-06-18 23:13
Reinstalled and it appears to work fine.  Very useful package!

**Comment by sinhrks** [comment] 2015-06-19 04:01
Thanks for the report:) Maybe caused by recent {scales} update? Closing as installation issue.

- http://cran.r-project.org/web/packages/scales/index.html

Pls feel free to lmk if anything you notice!

**Closed by sinhrks** 2015-06-19 04:01 UTC
