### ISSUE TITLE
ggsave doesn't recognize ggfortity objects

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [sinhrks/ggfortify#98] opened 2016-01-11 05:26 UTC
> plotdiag <-autoplot(result, which=c(1:3,5), mfrow=c(2,2))
> plotdiag
> ## ***partdiage;
> 
> ggsave(plot=plotdiag, file='cuckoo-R-diag.png', h=4, w=6, units="in", dpi=300)
> 
> returns
> Error in UseMethod("grid.draw") :
>   no applicable method for 'grid.draw' applied to an object of class "ggmultiplot"
> 
> I think Wickham modifies ggsave() to accept gtable objects. Do you create such an object? Perhaps add that as a class as well?
> 
> Using ggfortify 0.1.0 and ggplot 2.0.0

**Comment by terrytangyuan** [comment] 2016-08-02 16:15
Sorry for late reply. Could you include a reproducible example? Pull requests are welcomed!

**Comment by cschwarz-stat-sfu-ca** [comment] 2016-08-02 17:03
# Demonstrate problem with ggsave and ggfortify objects.

library(ggfortify)
library(ggplot2)

mydata <- data.frame( x=rnorm(10), y=rnorm(10))

fit <- lm(y~x, data=mydata)

# get the residual and other plots
diagplot <- autoplot(fit)
diagplot

ggsave(plot=diagplot, file='temp.png', h=6, w=6, units="in",dpi=300)


The last ggsave() gives:

> ggsave(plot=diagplot, file='temp.png', h=6, w=6, units="in",dpi=300)
Error in UseMethod("grid.draw") :
  no applicable method for 'grid.draw' applied to an object of class
"ggmultiplot"

If ggfortify extends ggplot2, presumably it should allow ggsave() to save
any created plots.

Thanks

Carl Schwarz

**Comment by terrytangyuan** [comment] 2016-08-02 20:46
Thanks! I noticed that `ggsave(file='temp.png', h=6, w=6, units="in",dpi=300)` works without specifying the plot. It just uses the last plot. I need to dig into ggplot2's code to see whether we can extend from there.

**Comment by terrytangyuan** [comment] 2016-08-02 20:55
@cschwarz-stat-sfu-ca Let's just use this workaround for now - print your plot first and then just call `ggsave` without specifying the plot. Otherwise, we'll have to look into ggplot2 or grid internals. Closing this for now unless you have other use cases that I may have missed.

**Comment by terrytangyuan** [comment] 2016-08-02 21:11
@cschwarz-stat-sfu-ca I posted an issue in ggplot2 here: https://github.com/hadley/ggplot2/issues/1692

**Comment by AndreaPi** [comment] 2016-11-25 18:23
Hi, any news on this? It still doesn't work - only the last of the 6 diagnostic plots gets saved, which is not what one needs. Thanks

**Comment by terrytangyuan** [comment] 2016-11-25 19:47
Thanks for the follow-up! We will fix it soon but the temporary solution is:

```
library(grid)
library(gridExtra)
ggsave(grid.draw(arrangeGrob(grobs = diagplot@plots)), file='temp.png', h=6, w=6, units="in",dpi=300)
```

Let me know if this fixed the issue!

**Comment by terrytangyuan** [comment] 2016-11-25 20:18
As Hadley mentioned in the other issue, it's because `grid.draw` needs to be implemented for `ggmultiplot` objects. Working on the fix now!

**Comment by terrytangyuan** [comment] 2016-11-25 20:27
Fixed here https://github.com/sinhrks/ggfortify/commit/beea00e54582ed0e2fb10b34e354dcc42f4fc4c5! @AndreaPi @cschwarz-stat-sfu-ca 

Closing this again. Let me know if you are still encountering any issues!

**Closed by terrytangyuan** 2016-11-25 20:27 UTC

**Comment by linlynn008** [comment] 2022-05-02 02:46
You do not need the plot=diagplot as the argument, just use: ggsave ('xplot.jpg')

**Comment by Max-Trouble** [comment] 2023-06-04 23:40
Is it just me or is it not working again? I am using CRANs ggfortify version 0.4.16.
For the following code 
```
autoplot(model, which = 1:4, label.size = 3) + theme_bw()
ggsave("model.png",width=22,height=15,units="cm",dpi=150)
``` 
it is just saving the last plot (Cook´s distance in my case) like in https://github.com/sinhrks/ggfortify/issues/98#issuecomment-237037986
